# Source: ghost/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata: # kpt-merge: ghost-ns/ghost-mariadb
  name: ghost-mariadb
  namespace: ghost-ns-marketing
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.6.1
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Helm
    apptype: 3p
    department: marketing
type: Opaque
data:
  mariadb-root-password: MDRJcGVTR3RrNg==
  mariadb-password: Q2RYTE1Ma0hZNQ==
