# Source: ghost/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: ghost-ns/ghost-mariadb
  name: ghost-mariadb
  namespace: ghost-ns-marketing
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.6.1
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Helm
    apptype: 3p
    department: marketing
