# Source: ghost/charts/mariadb/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata: # kpt-merge: ghost-ns/ghost-mariadb
  name: ghost-mariadb
  namespace: ghost-ns-marketing
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.6.1
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
    apptype: 3p
    department: marketing
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: ghost
    app.kubernetes.io/component: primary
    apptype: 3p
    department: marketing
